<!--EDIT-PANEL-->
<div class="w3-panel">
    <!--<div>ID: <span id="js-edit-cat-id"></span></div>-->
    <input id="js-edit-cat-id" class="w3-input" type="text" name=""/>
    <label>Наименование: </label>
    <input id="js-edit-cat-name" class="w3-input" type="text" name=""/>
    <button id="js-apply" class="w3-button w3-border">Применить</button>
    <button id="js-add" class="w3-button w3-border">Добавить</button>
</div>

<!--RECORDS-->
<div class="w3-responsive">
    <table id="js-table" class="w3-table  w3-striped w3-bordered w3-hoverable">
        <tr>
            <th class="w3-border-right w3-border-left w3-center">ID</th>
            <th class="w3-border-right w3-border-left w3-center">Наименование</th></th>
            <th class="w3-border-right w3-border-left w3-center">Управление</th></th>
        </tr>
    <?php foreach($categories as $cat) :?>
        <tr class="js-table-row">
            <td class="js-id w3-border-right w3-border-left"><?=$cat->id?></td>
            <td class="js-name w3-border-right w3-border-left"><?=$cat->name?></td>
            <td class="w3-border-right w3-border-left w3-center">
                <span js-edit-id="<?=$cat->id?>" class="js-delete w3-button w3-transparent w3-right w3-hover-black">&times;</span>
            </td>
        </tr>
    <?php endforeach;?>
    </table>
</div>

<script>
    $( document ).ready( function() {
        function handleUpdateSuccess(response) {
            var data = response.data;
            data = JSON.parse( data );
            var newId = data.updated.id;
            var newName = data.updated.name;
            
            $( ".js-table-row" ).each( function() {
                var $this = $(this);
                if ($this.find(".js-id").text() === newId) {
                    $this.find(".js-name").text(newName);
                }
            });
            
            console.log( data.updated );
        }
        
        function handleUpdateFail(response) {
            console.log('fail');
        }
        
        function handleRmSuccess(response) {
            var data = response.data;
            data = JSON.parse( data );
            var newId = data.updated;
            
            $( ".js-table-row" ).each( function() {
                var $this = $(this);
                if ($this.find(".js-id").text() === newId) {
                    // $this.addClass( "js-should-rm" );
                    $this.remove();
                }
            });
            
            console.log( data.updated );
        }
        
        function handleRmFail(response) {
            console.log('fail');
        }
        
        function handleAddSuccess(response) {
            var data = response.data;
            data = JSON.parse( data );
            var newId = data.updated.id;
            var newName = data.updated.name;
            
            $( "#js-table" ).append("\<tr class=\"js-table-row\">" +
                    "\<td class=\"js-id w3-border-right w3-border-left\">"+newId+"<\/td>" + 
                    "\<td class=\"js-name w3-border-right w3-border-left\">"+newName+"<\/td>" +
                    "<td class=\"w3-border-right w3-border-left w3-center\">"+
                    "<span js-edit-id=" + newId + " class=\"js-delete w3-button w3-transparent w3-right w3-hover-black\">&times;<\/span>" +
                    "<\/td><\/tr>"
            );
            
            console.log( data.updated );
        }
        
        function handleAddFail(response) {
            console.log('fail');
        }
        
        $(".js-delete").click( function() {
            var catId = $( this ).attr("js-edit-id");
            var data = "id=" + catId;
            
            console.log(data);
            $.ajax({
                type: 'POST',
                url: '/control/categories/rm',
                data: data,
                statusCode: {
                    200: handleRmSuccess,
                    400: handleRmFail
                }
            });
        });
        
        $("#js-add").click( function() {
            var catName = $( "#js-edit-cat-name" ).val();
            var data = "name=" + catName;
            
            $.ajax({
                type: 'POST',
                url: '/control/categories/add',
                data: data,
                statusCode: {
                    200: handleAddSuccess,
                    400: handleAddFail
                }
            });
        });
        
        $(".js-table-row").click( function() {
            var selected = $(this);
            var editId = $("#js-edit-cat-id");
            var editName = $("#js-edit-cat-name");
            
            editId.val( selected.find( ".js-id" ).text() );
            editName.val( selected.find( ".js-name" ).text() );
        });
        
        $("#js-apply").click( function() {
            var catId = $( "#js-edit-cat-id" ).val();
            var catName = $( "#js-edit-cat-name" ).val();
            var data = "id=" + catId + "&name=" + catName;
            
            console.log(data);
            $.ajax({
                type: 'POST',
                url: '/control/categories/update',
                data: data,
                statusCode: {
                    200: handleUpdateSuccess,
                    400: handleUpdateFail
                }
            });
        });
    });
</script>